### ISSUE TITLE
Decide if rubicon-java will support JNI global refs

### ISSUE THREAD

**Issue by paulproteus** [beeware/rubicon-java#38]
As I implement Toga support for Android, I notice that all `rubicon-java` object accesses are JNI local references. This means they work great within one call to Python, but that they can't really be stored and used by a later call from Java to Python.

I find this pretty OK, now that I know about it. I'm bullish on declaring that `rubicon-java` will avoid supporting JNI global refs. It means that we have less to worry about in terms of getting our references story right and testing that we're not creating object leaks for Java objects.

I think if we go this route, we may as well write in the `README` or elsewhere in the docs that we're taking this approach, just to clarify this for users (myself included).

Or we could decide to add support for JNI global refs.

Or we could decide to switch entirely from JNI local refs to JNI global refs.

Perhaps this is just a giant can of worms, and we can close this issue and not worry about it.

**Comment by freakboy3742** [comment]
I think I understand the problem you're describing, but I'm trying to think of a context where this will be an issue... have you got a specific case where this has come up, or is this just a case of defensive design?

**Comment by freakboy3742** [comment]
I think we've answered this one - Yes, we need global refs; and #59 will add some sugar to make it easier to do so.
